import { Quote } from '@/types';

export const MOCK_QUOTES: Quote[] = [
  {
    id: 1,
    cpo_id: 'CPO-2024-001',
    quote_number: 'QT-101',
    part_no: 'PN-C9200L-48T',
    sales_territory: 'South America',
    team: 'Team A',
    vendor_name: 'Cisco',
    master_customer_name: 'Revenda ABC',
    cpo_customer: 'CPO-CUST-001',
    end_user_company: 'TechCorp Brasil',
    quote_stage: 'Committed 75%',
    quote_name: 'Enterprise Network Suite Q1',
    cif_value_usd: 285000,
    probability_percentage: 75,
    projected_close_date: '2024-04-30',
    cpo_entry_datetime: '2024-03-01T10:30:00Z',
    available_credit: 285000,
    available_credit_usd: 285000,
    is_budgetary: false,
    is_lost: false,
    lost_reason: '',
    notes: 'Strategic account, high priority',
    created_at: '2024-03-01T10:30:00Z',
    updated_at: '2024-03-15T14:22:00Z',
  },
  {
    id: 2,
    cpo_id: 'CPO-2024-002',
    quote_number: 'QT-102',
    part_no: 'PN-HPE-DL380',
    sales_territory: 'Brazil Central',
    team: 'Team B',
    vendor_name: 'HPE',
    master_customer_name: 'Revenda XYZ',
    cpo_customer: 'CPO-CUST-002',
    end_user_company: 'DataSys Solutions',
    quote_stage: 'Up Selling 50%',
    quote_name: 'Server Infrastructure',
    cif_value_usd: 156000,
    probability_percentage: 50,
    projected_close_date: '2024-05-15',
    cpo_entry_datetime: '2024-02-20T08:15:00Z',
    available_credit: 156000,
    available_credit_usd: 156000,
    is_budgetary: true,
    is_lost: false,
    lost_reason: '',
    notes: 'Budget approved',
    created_at: '2024-02-20T08:15:00Z',
    updated_at: '2024-03-10T11:45:00Z',
  },
  {
    id: 3,
    cpo_id: 'CPO-2024-003',
    quote_number: 'QT-103',
    part_no: 'PN-VMWARE-SUITE',
    sales_territory: 'São Paulo',
    team: 'Team A',
    vendor_name: 'VMware',
    master_customer_name: 'Revenda Global',
    cpo_customer: 'CPO-CUST-003',
    end_user_company: 'CloudTech Innovations',
    quote_stage: 'Pricing 25%',
    quote_name: 'Virtualization Platform',
    cif_value_usd: 98000,
    probability_percentage: 25,
    projected_close_date: '2024-06-01',
    cpo_entry_datetime: '2024-03-05T09:00:00Z',
    available_credit: 98000,
    available_credit_usd: 98000,
    is_budgetary: false,
    is_lost: false,
    lost_reason: '',
    notes: 'Initial inquiry',
    created_at: '2024-03-05T09:00:00Z',
    updated_at: '2024-03-15T09:00:00Z',
  },
  {
    id: 4,
    cpo_id: 'CPO-2024-004',
    quote_number: 'QT-104',
    part_no: 'PN-NETAPP-STORAGE',
    sales_territory: 'South America',
    team: 'Team C',
    vendor_name: 'NetApp',
    master_customer_name: 'Revenda Master',
    cpo_customer: 'CPO-CUST-004',
    end_user_company: 'StorageCore Inc',
    quote_stage: 'Committed 75%',
    quote_name: 'Storage Infrastructure',
    cif_value_usd: 425000,
    probability_percentage: 75,
    projected_close_date: '2024-04-15',
    cpo_entry_datetime: '2024-02-10T14:20:00Z',
    available_credit: 425000,
    available_credit_usd: 425000,
    is_budgetary: false,
    is_lost: false,
    lost_reason: '',
    notes: 'Large deal',
    created_at: '2024-02-10T14:20:00Z',
    updated_at: '2024-03-14T16:30:00Z',
  },
  {
    id: 5,
    cpo_id: 'CPO-2024-005',
    quote_number: 'QT-105',
    part_no: 'PN-DELL-POWEREDGE',
    sales_territory: 'Rio de Janeiro',
    team: 'Team B',
    vendor_name: 'Dell',
    master_customer_name: 'Revenda Premium',
    cpo_customer: 'CPO-CUST-005',
    end_user_company: 'NetVision Brazil',
    quote_stage: 'Pipelined',
    quote_name: 'Server Bundle Package',
    cif_value_usd: 185000,
    probability_percentage: 10,
    projected_close_date: '2024-07-01',
    cpo_entry_datetime: '2024-03-10T10:00:00Z',
    available_credit: 185000,
    available_credit_usd: 185000,
    is_budgetary: false,
    is_lost: false,
    lost_reason: '',
    notes: 'Prospect stage',
    created_at: '2024-03-10T10:00:00Z',
    updated_at: '2024-03-15T10:00:00Z',
  },
  {
    id: 6,
    cpo_id: 'CPO-2024-006',
    quote_number: 'QT-106',
    part_no: 'PN-CISCO-SWITCHES',
    sales_territory: 'Minas Gerais',
    team: 'Team A',
    vendor_name: 'Cisco',
    master_customer_name: 'Revenda Tech',
    cpo_customer: 'CPO-CUST-006',
    end_user_company: 'NetworkPlus',
    quote_stage: 'Net Lost',
    quote_name: 'Network Switches',
    cif_value_usd: 75000,
    probability_percentage: 0,
    projected_close_date: '2024-03-30',
    cpo_entry_datetime: '2024-02-28T11:30:00Z',
    available_credit: 0,
    available_credit_usd: 0,
    is_budgetary: false,
    is_lost: true,
    lost_reason: 'Competitor',
    notes: 'Lost to competitor',
    created_at: '2024-02-28T11:30:00Z',
    updated_at: '2024-03-14T15:00:00Z',
  },
];

// Generate 50 quotes with variations
export function generateMockQuotes(): Quote[] {
  const quotes = [...MOCK_QUOTES];
  const stages: Quote['quote_stage'][] = ['Pipelined', 'Pricing 25%', 'Up Selling 50%', 'Committed 75%', 'Net Lost'];
  const vendors = ['Cisco', 'HPE', 'VMware', 'NetApp', 'Dell', 'Juniper', 'Arista', 'F5'];
  const territories = ['South America', 'Brazil Central', 'São Paulo', 'Rio de Janeiro', 'Minas Gerais', 'Bahia'];
  const teams = ['Team A', 'Team B', 'Team C', 'Team D'];

  for (let i = 7; i <= 50; i++) {
    const stage = stages[Math.floor(Math.random() * stages.length)];
    const probability = stage === 'Pipelined' ? 10 : stage === 'Pricing 25%' ? 25 : stage === 'Up Selling 50%' ? 50 : stage === 'Committed 75%' ? 75 : 0;
    const baseValue = Math.floor(Math.random() * 400000) + 50000;

    quotes.push({
      id: i,
      cpo_id: `CPO-2024-${String(i).padStart(3, '0')}`,
      quote_number: `QT-${String(100 + i).padStart(3, '0')}`,
      part_no: `PN-${vendors[Math.floor(Math.random() * vendors.length)]}-${i}`,
      sales_territory: territories[Math.floor(Math.random() * territories.length)],
      team: teams[Math.floor(Math.random() * teams.length)],
      vendor_name: vendors[Math.floor(Math.random() * vendors.length)],
      master_customer_name: `Revenda ${String.fromCharCode(65 + (i % 26))}`,
      cpo_customer: `CPO-CUST-${i}`,
      end_user_company: `Company-${i}`,
      quote_stage: stage,
      quote_name: `Quote Project ${i}`,
      cif_value_usd: baseValue,
      probability_percentage: probability,
      projected_close_date: new Date(Date.now() + Math.random() * 90 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      cpo_entry_datetime: new Date(Date.now() - Math.random() * 60 * 24 * 60 * 60 * 1000).toISOString(),
      available_credit: probability > 0 ? baseValue : 0,
      available_credit_usd: probability > 0 ? baseValue : 0,
      is_budgetary: Math.random() > 0.7,
      is_lost: stage === 'Net Lost',
      lost_reason: stage === 'Net Lost' ? ['Competitor', 'Budget', 'Postponed'][Math.floor(Math.random() * 3)] : '',
      notes: `Note for quote ${i}`,
      created_at: new Date(Date.now() - Math.random() * 60 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    });
  }

  return quotes;
}
